name: Main

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: 'dev'
      - run: flutter config --enable-macos-desktop
      - run: cd example && flutter packages get && flutter build macos -v

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: 'dev'
      - run: |
          Get-Command flutter | Get-Item | Split-Path | Set-Location; Set-Location ..
          git clean -xdf; git fetch; git checkout -b master
          flutter config --enable-windows-desktop
          cd -
      - run: cd example; flutter packages get && flutter build windows
        continue-on-error: true
      - uses: warrenbuckley/Setup-Nuget@v1
      - run: cd example\windows; nuget restore; cd -
      - run: cd example; flutter packages get; flutter build windows -v